# Generated by Django 2.2 on 2021-05-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_duan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('monitor_time', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
