# Generated by Django 2.2 on 2021-06-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_db_duan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_duan',
            name='url',
        ),
        migrations.AddField(
            model_name='db_duan',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='db_duan',
            name='monitor_dingtalk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_duan',
            name='monitor_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='db_duan',
            name='monitor_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='db_duan',
            name='monitor_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='db_href',
            name='url',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
