# Generated by Django 2.2 on 2021-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20210606_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('duan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('BF', models.BooleanField(default=True)),
                ('JK', models.BooleanField(default=True)),
                ('py', models.CharField(blank=True, max_length=20, null=True)),
                ('counts', models.IntegerField(default=1)),
            ],
        ),
    ]
