# Generated by Django 2.2 on 2021-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_db_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_duan',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
