# Generated by Django 2.2 on 2021-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_db_duan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_duan',
            name='max_bf',
            field=models.IntegerField(default=5),
        ),
    ]
