# Generated by Django 2.2 on 2021-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_db_duan_max_bf'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_duan',
            name='monitor_host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
