# Generated by Django 2.2 on 2021-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_db_duan_monitor_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_quanxian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('users', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
