# Generated by Django 2.2 on 2021-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_db_quanxian'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duan_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=300, null=True)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
    ]
