# Generated by Django 2.2 on 2021-07-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_db_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_object',
            name='tmp_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='db_object',
            name='tmp_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
